---
name: Publish to GitHub
run-name: Publish to GitHub
on:
  workflow_dispatch:
  push:

jobs:
  Publish-To-Github:
    uses: https://github.com/james9001/james9001-workflows/.gitea/workflows/github-publish.yaml@a685bcf8f9b514b08dfc8262894dc3a45252dceb
    with:
      github_user_name: james9001
      github_user_email: james9001@james9001.net
    secrets:
      GITHUB_USER_CREDENTIALS: ${{ secrets.JAMES9001_GITHUB_CREDENTIALS }}
